In [ ]:
!git clone https://github.com/RUCAIBox/HaluEval.git

Cloning into 'HaluEval'...
remote: Enumerating objects: 166, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 166 (delta 37), reused 33 (delta 9), pack-reused 70
Receiving objects: 100% (166/166), 37.92 MiB | 11.22 MiB/s, done.
Resolving deltas: 100% (62/62), done.
Updating files: 100% (38/38), done.


In [ ]:
!pip install transformers[torch]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 261.4/261.4 kB 4.7 MB/s eta 0:00:00


In [1]:
import pickle
# import graphvite as gv
#import dataset
import nltk
import re
import spacy
import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from nltk.tag import pos_tag
from nltk.chunk import ne_chunk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to
[nltk_data]     /var/home/zaristei/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /var/home/zaristei/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /var/home/zaristei/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     /var/home/zaristei/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /var/home/zaristei/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [2]:
!pip install transformers
from transformers import AutoModelForQuestionAnswering, AutoTokenizer

In [3]:
from transformers import TrainingArguments, Trainer
from huggingface_hub import notebook_login

notebook_login()

In [ ]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 521.2/521.2 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 12.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 7.2 MB/s eta 0:00:00


In [4]:
!wget -O processed_data.pkl 'https://www.dropbox.com/scl/fi/vp5c9hcyqnaottfre5yas/processed_data.pkl?rlkey=i0gko0chfwyj5fn4rhsx9o3ve&dl=0'
!wget -O neighbours.pkl 'https://www.dropbox.com/scl/fi/lw1d9mlr7laf7wo5ladvu/neighbours-Zack.pkl?rlkey=s81bm5oxh8oy0hmziq8rbxh84&dl=0'

--2023-11-30 06:33:57--  https://www.dropbox.com/scl/fi/vp5c9hcyqnaottfre5yas/processed_data.pkl?rlkey=i0gko0chfwyj5fn4rhsx9o3ve&dl=0
Resolving www.dropbox.com (www.dropbox.com)... 2620:100:601f:18::a27d:912, 162.125.9.18
Connecting to www.dropbox.com (www.dropbox.com)|2620:100:601f:18::a27d:912|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://uc3e9ad18afcc2119cd284bc00a8.dl.dropboxusercontent.com/cd/0/inline/CIhjwXrGDCY1IEq8IrdjcTI996tPX5HH4MtsZ9l5LIbPUlvbjulxEZe5b0Yu0j7QN9cCWrnhb4FsaVYVC80qeb4zGxtUOvRRVn_YIX5mW_Qft7HeSSOm7UP2O-3dguVA3FKUfN7_IragBWzBX3dJmA01/file# [following]
--2023-11-30 06:33:57--  https://uc3e9ad18afcc2119cd284bc00a8.dl.dropboxusercontent.com/cd/0/inline/CIhjwXrGDCY1IEq8IrdjcTI996tPX5HH4MtsZ9l5LIbPUlvbjulxEZe5b0Yu0j7QN9cCWrnhb4FsaVYVC80qeb4zGxtUOvRRVn_YIX5mW_Qft7HeSSOm7UP2O-3dguVA3FKUfN7_IragBWzBX3dJmA01/file
Resolving uc3e9ad18afcc2119cd284bc00a8.dl.dropboxusercontent.com (uc3e9ad18afcc2119cd284bc00a8.dl.dropboxusercontent.com

In [5]:
# !wget -O simple_wikidata5m.pkl https://udemontreal-my.sharepoint.com/:u:/g/personal/zhaocheng_zhu_umontreal_ca/EVcJpJAzkThPu1vjgJLohscBgwtPajhTZvCCd8nEg1GiwA?download=1
# !wget -O entity.txt.gz https://www.dropbox.com/s/bgmgvk8brjwpc9w/entity.txt.gz?dl=1
!wget -O neighbour_embs.pkl 'https://www.dropbox.com/scl/fi/0ts9lajzorxfbyse3ogj5/neighbours-Santa-Claus.pkl?rlkey=6jq6ezx65kp7tqp8kekf6tvf1&dl=0'

--2023-11-30 06:34:20--  https://www.dropbox.com/scl/fi/0ts9lajzorxfbyse3ogj5/neighbours-Santa-Claus.pkl?rlkey=6jq6ezx65kp7tqp8kekf6tvf1&dl=0
Resolving www.dropbox.com (www.dropbox.com)... 2620:100:601f:18::a27d:912, 162.125.9.18
Connecting to www.dropbox.com (www.dropbox.com)|2620:100:601f:18::a27d:912|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://uc01bb4c5bb5eb75c8bf1b37cb5c.dl.dropboxusercontent.com/cd/0/inline/CIj74qPfS9TyJ-kkd4aVYtSCiawETNmgbH12ZybUr-Snf4dvxuc58A7dAsrD2Gi3OqcFlqDYGpEtcTFOdbEI-0rDd1CMOeJUPqg-y6FZxKwoQZctSup9rwHy4hJYUoxldgebcV0Xkupm_XqZQLC7YjM4/file# [following]
--2023-11-30 06:34:20--  https://uc01bb4c5bb5eb75c8bf1b37cb5c.dl.dropboxusercontent.com/cd/0/inline/CIj74qPfS9TyJ-kkd4aVYtSCiawETNmgbH12ZybUr-Snf4dvxuc58A7dAsrD2Gi3OqcFlqDYGpEtcTFOdbEI-0rDd1CMOeJUPqg-y6FZxKwoQZctSup9rwHy4hJYUoxldgebcV0Xkupm_XqZQLC7YjM4/file
Resolving uc01bb4c5bb5eb75c8bf1b37cb5c.dl.dropboxusercontent.com (uc01bb4c5bb5eb75c8bf1b37cb5c.dl.dropboxusercon

In [6]:
processed_file = open("processed_data.pkl", "rb")
graph_data = pickle.load(processed_file)
neighbours_file = open("neighbours.pkl", "rb")
neighbours = pickle.load(neighbours_file)
neighbour_embs_file = open("neighbour_embs.pkl", "rb")
neighbour_embs = pickle.load(neighbour_embs_file)

In [7]:
file = open("simple_wikidata5m.pkl", "rb")
model = pickle.load(file)
entity2id = model.graph.entity2id
relation2id = model.graph.relation2id
entity_embeddings = model.solver.entity_embeddings
relation_embeddings = model.solver.relation_embeddings
alias2entity = dataset.wikidata5m.load_alias("./entity.txt.gz")

NameError: name 'dataset' is not defined

In [8]:
entity2id = graph_data.graph.entity2id
relation2id = graph_data.graph.relation2id
entity_embeddings = graph_data.solver.entity_embeddings
relation_embeddings = graph_data.solver.relation_embeddings

AttributeError: 'list' object has no attribute 'graph'

In [9]:
import json

# Opening JSON file
data_list = []
with open('HaluEval/data/qa_data.json') as json_file:
    for jsonObj in json_file:
        data_dict = json.loads(jsonObj)
        data_list.append(data_dict)



In [10]:
connection_dict = {obj["question"].strip().lower() : i for i, obj in enumerate(data_list)}

In [11]:
len(connection_dict)

10000

In [12]:
from datasets import load_dataset

def get_data(data_path):

  ds = load_dataset("json", data_files=data_path, split="train")
  ds = ds.train_test_split(test_size=0.2)
  return ds

#print(os.listdir())

ds = get_data("HaluEval/data/qa_data.json")
print(ds)

Found cached dataset json (/var/home/zaristei/.cache/huggingface/datasets/json/default-870d2fc0789b4dbd/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)


DatasetDict({
    train: Dataset({
        features: ['knowledge', 'question', 'right_answer', 'hallucinated_answer'],
        num_rows: 8000
    })
    test: Dataset({
        features: ['knowledge', 'question', 'right_answer', 'hallucinated_answer'],
        num_rows: 2000
    })
})


In [22]:
print(neighbour_embs[0]["portland, oregon"]["embedding"].shape)
emb_average = torch.empty((512,), dtype=torch.int64)

for key in neighbour_embs[1683]:
    emb_average += neighbour_embs[1683][key]["embedding"] / len(neighbour_embs[1683])

print(emb_average, emb_average.shape)

(512,)
tensor([ 5.6121e+07,  1.4034e+14,  3.8655e+10,  4.5382e-02,  1.3927e+01,
         1.4034e+14, -4.2950e+09,  5.6123e+07,  1.4034e+14,  4.7245e+10,
         5.5954e+01, -9.2334e-01,  9.9880e+00, -4.2950e+09,  5.6124e+07,
         1.4034e+14,  4.7245e+10,  1.1203e+02,  8.9330e+00,  1.4033e+14,
        -4.2950e+09,  5.6124e+07,  1.4034e+14,  4.7245e+10,  1.6796e+02,
         5.2521e-03,  1.4033e+14, -4.2950e+09,  5.6124e+07,  1.4034e+14,
         4.7245e+10,  2.2410e+02, -3.7569e-02,  1.4033e+14, -4.2950e+09,
         5.6124e+07,  1.4034e+14,  3.0065e+10,  2.7992e+02,  1.4034e+14,
         2.3763e-03, -4.9848e-04,  3.8321e-02,  1.4323e-01, -9.4150e-02,
         1.1430e-01, -1.4697e-01, -1.1065e-01, -7.3059e-02,  1.4034e+14,
        -1.1392e-02,  1.0732e-01, -7.3572e-02,  6.2806e-03, -2.9468e-02,
         4.5505e-03,  2.2395e-02, -4.5406e-02,  1.6994e-02, -3.2594e-02,
         3.0986e-02,  3.1456e-02, -7.6332e-02, -1.4383e-01,  4.3087e-02,
         1.4034e+14,  2.4115e-02, -2.4778e-0

In [114]:
import torch
import numpy as np

def preprocess_function(examples):
  questions = [q.strip().lower() for q in examples["question"]]
  inputs = tokenizer(
      questions,
      [c.lower() for c in examples["knowledge"]],
      max_length=384,
      truncation="only_second",
      return_offsets_mapping=True,
      padding="max_length",
  )
  offset_mapping = inputs.pop("offset_mapping")
  answers = examples["right_answer"]
  start_positions = []
  end_positions = []
  graph_embeddings = []
  neighbours_embeddings = []

  for i, offset in enumerate(offset_mapping):
      answer = answers[i]
      start_char = examples["knowledge"][i].find(answer)
      end_char = start_char + len(answer)
      sequence_ids = inputs.sequence_ids(i)

      # Find the start and end of the context
      idx = 0
      while sequence_ids[idx] != 1:
          idx += 1
      context_start = idx
      while sequence_ids[idx] == 1:
          idx += 1
      context_end = idx - 1

      # If the answer is not fully inside the context, label it (0, 0)
      if offset[context_start][0] > end_char or offset[context_end][1] < start_char:
          start_positions.append(0)
          end_positions.append(0)
      else:
          # Otherwise it's the start and end token positions
          idx = context_start
          while idx <= context_end and offset[idx][0] <= start_char:
              idx += 1
          start_positions.append(idx - 1)

          idx = context_end
          while idx >= context_start and offset[idx][1] >= end_char:
              idx -= 1
          end_positions.append(idx + 1)

      corr_index = connection_dict[questions[i]]
      graph_index = graph_data[corr_index]
      embeddings = torch.zeros(384, 512)
      neighbours_list_index = corr_index
      emb_average = torch.zeros(512)
      token_list = inputs.input_ids[i]
      for ent, embedding in graph_index["knowledge"].items():
          ent_token_list = [tokenizer(ent).input_ids[1:-1], tokenizer(" " + ent).input_ids[1:-1]]

          for i in range(len(token_list) - len(list(ent_token_list)[0])):
            if token_list[i:i+len(list(ent_token_list)[0])] in ent_token_list:
              embeddings[i:i+len(list(ent_token_list)[0]), :] = torch.broadcast_to(torch.from_numpy(embedding), (len(list(ent_token_list)[0]), 512))
      for ent, embedding in graph_index["question"].items():
          ent_token_list = [tokenizer(ent).input_ids[1:-1], tokenizer(" " + ent).input_ids[1:-1]]

          for i in range(len(token_list) - len(list(ent_token_list)[0])):
            if token_list[i:i+len(list(ent_token_list)[0])] in ent_token_list:
              embeddings[i:i+len(list(ent_token_list)[0]), :] = torch.broadcast_to(torch.from_numpy(embedding), (len(list(ent_token_list)[0]), 512))
      graph_embeddings.append(embeddings)
      for key in neighbour_embs[neighbours_list_index]:
          emb_average += torch.from_numpy(neighbour_embs[neighbours_list_index][key]["embedding"].astype(np.float32)) / len(neighbour_embs[neighbours_list_index])
      neighbours_embeddings.append(emb_average)


  inputs["start_positions"] = start_positions
  inputs["end_positions"] = end_positions
  inputs["graph_embeddings"] = graph_embeddings
  inputs["avg_neighbour_embeddings"] = neighbours_embeddings

  return inputs

In [115]:
ds["train"][1]

{'knowledge': 'The "Comic Relief special" was an edition of the BBC sit-com, "Only Fools and Horses", recorded as part of the 1997 Comic Relief appeal. This special was the final appearance of Uncle Albert.Only Fools and Horses is a British television sitcom created and written by John Sullivan. Seven series were originally broadcast on BBC One in the United Kingdom from 1981 to 1991, with sixteen sporadic Christmas specials aired until the end of the show in 2003.',
 'question': "Who wrote the British television sitcom with seven series being broadcast between 1981 to 1991, 16 sporadic Christmas specials, and a 'Comic Relief special', recorded as part of the 1997 appeal which features the final appearance of Uncle Albert?",
 'right_answer': 'John Sullivan',
 'hallucinated_answer': 'The author of "Only Fools and Horses".'}

In [116]:
print(ds["train"][1]["question"].strip())
corr_index = connection_dict[ds["train"][1]["question"].strip().lower()]
print(corr_index)
#print(graph_data[corr_index])
graph_index = graph_data[corr_index]
#for ent, embedding in graph_index["knowledge"].items():
#    graph_embeddings.append(embedding)
model_name = "deepset/roberta-base-squad2"
tokenizer = AutoTokenizer.from_pretrained(model_name)

for k, v in graph_index["question"].items():
  print("{}, {}, {}".format(k, tokenizer(k).input_ids[1:-1], tokenizer(" " + k).input_ids[1:-1]))
for k, v in graph_index["knowledge"].items():
  print("{}, {}, {}".format(k, tokenizer(k).input_ids[1:-1], tokenizer(" " + k).input_ids[1:-1]))
print(tokenizer("Teen Wolf"))
print(str(tokenizer.decode([664, 2143, 417])) + "," + str(tokenizer.decode([39556])))

Who wrote the British television sitcom with seven series being broadcast between 1981 to 1991, 16 sporadic Christmas specials, and a 'Comic Relief special', recorded as part of the 1997 appeal which features the final appearance of Uncle Albert?
7140
british, [428, 3961, 1173], [741, 3961, 1173]
seven, [17723], [707]
between 1981 to 1991, [25784, 14130, 7, 9633], [227, 14130, 7, 9633]
16, [1549], [545]
christmas, [27790, 13738], [29224, 13738]
1997, [40954], [7528]
uncle albert, [45711, 1076, 6747], [11992, 1076, 6747]
bbc, [14141, 438], [741, 23219]
1997, [40954], [7528]
uncle albert, [45711, 1076, 6747], [11992, 1076, 6747]
fools, [506, 22890], [38201]
british, [428, 3961, 1173], [741, 3961, 1173]
john sullivan, [25304, 2628, 890, 18356], [41906, 2628, 890, 18356]
seven, [17723], [707]
bbc one, [14141, 438, 65], [741, 23219, 65]
the united kingdom, [627, 10409, 11673], [5, 10409, 11673]
1981, [44582], [14130]
1991, [42478], [9633]
sixteen, [13664, 13665], [32382]
christmas, [27790, 

In [117]:
example = {
    "knowledge": [ds["train"][1]["knowledge"]],
    "question": [ds["train"][1]["question"]],
    "right_answer": [ds["train"][1]["right_answer"]],
    "hallucinated_answer": [ds["train"][1]["hallucinated_answer"]]
}
#print(clean_text(example))
model_name = "deepset/roberta-base-squad2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
inputs = preprocess_function(example)
print([(k, type(val)) for k, val in inputs.items()])
print(len(inputs['graph_embeddings'][0][0]))
print(tokenizer.decode(inputs["input_ids"][0]))

[('input_ids', <class 'list'>), ('attention_mask', <class 'list'>), ('start_positions', <class 'list'>), ('end_positions', <class 'list'>), ('graph_embeddings', <class 'list'>), ('avg_neighbour_embeddings', <class 'list'>)]
512
<s>who wrote the british television sitcom with seven series being broadcast between 1981 to 1991, 16 sporadic christmas specials, and a 'comic relief special', recorded as part of the 1997 appeal which features the final appearance of uncle albert?</s></s>the "comic relief special" was an edition of the bbc sit-com, "only fools and horses", recorded as part of the 1997 comic relief appeal. this special was the final appearance of uncle albert.only fools and horses is a british television sitcom created and written by john sullivan. seven series were originally broadcast on bbc one in the united kingdom from 1981 to 1991, with sixteen sporadic christmas specials aired until the end of the show in 2003.</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><p

In [118]:
ds['train']

Dataset({
    features: ['knowledge', 'question', 'right_answer', 'hallucinated_answer'],
    num_rows: 8000
})

In [119]:
model_name = "deepset/roberta-base-squad2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenized_ds = ds.map(preprocess_function, batched=True, remove_columns=ds["train"].column_names)

Map:   0%|          | 0/8000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [120]:
neighbour_embs[0]['ix century']['embedding'].shape

(512,)

In [121]:
#print(tokenized_ds["train"][0])
print(tokenized_ds["train"][0]["graph_embeddings"])
print(len(tokenized_ds["train"][0]["graph_embeddings"]))
print(len(tokenized_ds["train"][0]["graph_embeddings"][0]))
# print(tokenized_ds["train"]["end_positions"][0:10])

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0

In [122]:
from transformers import DefaultDataCollator

data_collator = DefaultDataCollator()

In [189]:
import torch
from torch import nn
import torch.nn.functional as F
from torch.nn import CrossEntropyLoss
from transformers.modeling_outputs import QuestionAnsweringModelOutput

class GraphEnrichedRoberta(nn.Module):
  def __init__(self, model_name):
    super().__init__()
    self.llm_embedding_size = 768
    self.graph_embedding_size = 512
    self.llm = AutoModelForQuestionAnswering.from_pretrained(model_name)
    self.fc = nn.Linear(self.graph_embedding_size + self.llm_embedding_size, self.llm_embedding_size)
    self.fc2 = nn.Linear(self.llm_embedding_size + self.graph_embedding_size, self.llm_embedding_size)
    self.fc3 = nn.Linear(self.graph_embedding_size, self.llm_mbedding_size)

    for param in self.llm.roberta.encoder.parameters():
      param.requires_grad = False

  def forward(self, input_ids, attention_mask, start_positions, end_positions, graph_embeddings, avg_neighbour_embeddings):
     outputs = self.llm.roberta(input_ids, attention_mask)
     sequence_outputs = outputs.last_hidden_state

     enriched_encodings = self.fc(torch.cat((sequence_outputs, graph_embeddings), 2))
     enriched_encodings = F.relu(enriched_encodings)
     final_encodings = self.fc(torch.cat((enriched_encodings, avg_neighbour_embeddings.unsqueeze(1).broadcast_to((enriched_encodings.shape[0], enriched_encodings.shape[1], self.graph_embedding_size))), 2))
     final_encodings = F.relu(final_encodings)

     logits = self.llm.qa_outputs(final_encodings)
     start_logits, end_logits = logits.split(1, dim=-1)
     start_logits = start_logits.squeeze(-1).contiguous()
     end_logits = end_logits.squeeze(-1).contiguous()

     total_loss = None
     if start_positions is not None and end_positions is not None:
          # If we are on multi-GPU, split add a dimension
         if len(start_positions.size()) > 1:
             start_positions = start_positions.squeeze(-1)
         if len(end_positions.size()) > 1:
             end_positions = end_positions.squeeze(-1)
          # sometimes the start/end positions are outside our model inputs, we ignore these terms
         ignored_index = start_logits.size(1)
         start_positions = start_positions.clamp(0, ignored_index)
         end_positions = end_positions.clamp(0, ignored_index)

         loss_fct = CrossEntropyLoss(ignore_index=ignored_index)
         start_loss = loss_fct(start_logits, start_positions)
         end_loss = loss_fct(end_logits, end_positions)
         total_loss = (start_loss + end_loss) / 2

     return QuestionAnsweringModelOutput(
         loss=total_loss,
         start_logits=start_logits,
         end_logits=end_logits,
         hidden_states=outputs.hidden_states,
         attentions=outputs.attentions,
     )

In [190]:
model = GraphEnrichedRoberta(model_name)

AttributeError: 'GraphEnrichedRoberta' object has no attribute 'llm_mbedding_size'

In [ ]:
with torch.no_grad():
  input_ids_test = torch.tensor(tokenized_ds["train"][0]["input_ids"]).unsqueeze(0)
  attn_mask_test = torch.tensor(tokenized_ds["train"][0]["attention_mask"]).unsqueeze(0)
  start_positions_test = torch.tensor(tokenized_ds["train"][0]["start_positions"]).unsqueeze(0)
  end_positions_test = torch.tensor(tokenized_ds["train"][0]["end_positions"]).unsqueeze(0)
  graph_embeddings_test = torch.tensor(tokenized_ds["train"][0]["graph_embeddings"]).unsqueeze(0)
  print(model(input_ids_test, attn_mask_test, start_positions_test, end_positions_test, graph_embeddings_test))

TypeError: GraphEnrichedRoberta.forward() missing 1 required positional argument: 'avg_neighbour_embeddings'

In [191]:
training_args = TrainingArguments(
    output_dir="roberta_qa_model_with_graph",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    push_to_hub=True,
    remove_unused_columns=False
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    eval_dataset=tokenized_ds["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
)

In [192]:
trainer.train()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (6144x1536 and 1280x768)

In [ ]:
torch.save(model.state_dict(), 'graph_model_weights.pth')

In [ ]:
model.load_state_dict(torch.load('graph_model_weights.pth'))

<All keys matched successfully>

In [ ]:
model

GraphEnrichedRoberta(
  (llm): RobertaForQuestionAnswering(
    (roberta): RobertaModel(
      (embeddings): RobertaEmbeddings(
        (word_embeddings): Embedding(50265, 768, padding_idx=1)
        (position_embeddings): Embedding(514, 768, padding_idx=1)
        (token_type_embeddings): Embedding(1, 768)
        (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (encoder): RobertaEncoder(
        (layer): ModuleList(
          (0-11): 12 x RobertaLayer(
            (attention): RobertaAttention(
              (self): RobertaSelfAttention(
                (query): Linear(in_features=768, out_features=768, bias=True)
                (key): Linear(in_features=768, out_features=768, bias=True)
                (value): Linear(in_features=768, out_features=768, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (output): RobertaSelfOutput(
                (dense): 

In [ ]:
#tokenized_ds["test"]

predictions = trainer.predict(tokenized_ds["test"].remove_columns(["graph_embeddings"]))

In [ ]:
import numpy as np

for i in range(len(predictions.predictions)):
  print(predictions.predictions[i].shape)

print(predictions.predictions[0])

print(np.array(tokenized_ds["test"]["start_positions"]).shape)


(125,)
(2000, 384)
(2000, 384)
[1.0641084  1.6659701  1.9759023  1.2464397  1.970095   1.2182294
 1.7953851  1.3778882  1.089099   2.3120296  1.0138576  1.7308497
 1.5308025  1.2966044  1.4876668  0.62224865 2.2005458  1.19306
 1.9669992  1.8536528  2.293821   1.792011   0.7256372  1.629729
 2.1631832  1.4701074  1.4578855  1.6019956  1.2260633  1.738751
 2.4187698  1.3923588  1.9579014  1.3781996  2.456057   1.0412458
 1.7440045  1.8541543  2.8645754  0.93838847 1.7694396  1.6841547
 1.9321573  1.4411316  1.38648    1.194206   0.81366175 1.0065814
 0.8059305  1.9596742  0.79150534 1.9571393  0.9703902  1.6299062
 1.890945   1.146168   1.0196122  1.1374956  2.0560458  1.7159839
 1.968475   1.3967826  1.6296978  1.5666738  1.2158916  1.7590964
 2.4377935  1.9311898  1.9091766  2.4590755  1.9080064  1.0684565
 1.7132566  2.3912418  1.6143143  1.9749919  1.1747274  1.9486256
 1.5132129  1.6976893  1.2747147  1.1367294  2.944383   1.1048306
 1.9857776  1.3243711  1.0923741  1.5487192  1.53

In [ ]:
avg_loss = np.mean(predictions.predictions[0])
avg_loss

1.6121981

In [ ]:
start_logits = predictions.predictions[1]
end_logits = predictions.predictions[2]

start_positions = np.array(tokenized_ds["test"]["start_positions"])
end_positions = np.array(tokenized_ds["test"]["end_positions"])

In [ ]:
start_positions_pred = np.argmax(start_logits, axis=1)
end_positions_pred = np.argmax(end_logits, axis=1)

In [ ]:
print(start_positions_pred)
print(start_positions)
print(end_positions_pred)
print(end_positions)
print(np.sum(start_positions_pred == start_positions))
overlap = np.maximum(0.0, np.minimum(end_positions_pred, end_positions) - np.maximum(start_positions_pred, start_positions) + 1)
print(overlap)
val1 = np.abs(1.0 * overlap / (end_positions - start_positions + 1))
val2 = np.abs(1.0 * overlap / (end_positions_pred - start_positions_pred + 1))
print(np.min(val1))
print(np.max(val1))
print(np.min(val2))
print(np.max(val2))

[ 39  55  97 ... 127  51  24]
[ 39  55  97 ... 127  51  24]
[ 42  57 102 ... 130  56  29]
[ 42  57 102 ... 130  56  29]
1165
[4. 3. 6. ... 4. 6. 6.]
0.0
1.0
0.0
1.0


In [ ]:
def exact_match(start_logits, end_logits, start_positions, end_positions):
  start_positions_pred = np.argmax(start_logits, axis=1)
  end_positions_pred = np.argmax(end_logits, axis=1)
  same_start = start_positions_pred == start_positions
  same_end = end_positions_pred == end_positions
  return np.sum(np.logical_and(same_start, same_end)) / start_positions.shape[0]

In [ ]:
exact_match(start_logits, end_logits, start_positions, end_positions)

0.505

In [ ]:
def f1_score(start_logits, end_logits, start_positions, end_positions):
  start_positions_pred = np.argmax(start_logits, axis=1)
  end_positions_pred = np.argmax(end_logits, axis=1)
  overlap = np.maximum(0, np.minimum(end_positions_pred, end_positions) - np.maximum(start_positions_pred, start_positions) + 1)
  recall = np.abs(1.0 * overlap / (end_positions - start_positions + 1))
  precision = np.abs(1.0 * overlap / (end_positions_pred - start_positions_pred + 1))
  f1 = (2 * precision * recall) / (precision + recall + 0.00000001)
  return np.mean(f1)

In [ ]:
f1_score(start_logits, end_logits, start_positions, end_positions)

0.6002186955899961

In [ ]:
import torch
from torch import nn
import torch.nn.functional as F

class GraphEnrichedRoberta(nn.Module):
  def __init__(self, model_name):
    super().__init__()
    self.llm_embedding_size = 768
    self.llm = AutoModelForQuestionAnswering.from_pretrained(model_name)

    for param in self.llm.roberta.encoder.parameters():
      param.requires_grad = False

  def forward(self, input_ids, attention_mask, start_positions, end_positions):
    return self.llm(input_ids=input_ids, attention_mask=attention_mask, start_positions=start_positions, end_positions=end_positions)

In [ ]:
model = GraphEnrichedRoberta(model_name)

In [ ]:
model.load_state_dict(torch.load('model_weights.pth'))

<All keys matched successfully>